CREATE TABLE  IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM("user", "admin") DEFAULT "user",
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);