CREATE TABLE sessions(
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP, INTERVAL 24 HOURS),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
)